AllCops:
  NewCops: enable
  Exclude:
    - '.git/**/*'
    - 'core/**/*'
    - 'pkg/**/*'
    - 'stock/**/*'

Layout/LineLength:
  Max: 110
  IgnoredPatterns:
    - '\A\s*spec\.add_\w+_dependency'

# TODO: Set to true and use auto-correct, and
#       then set to false to see Heredoc offenses.
Layout/TrailingWhitespace:
  AllowInHeredoc: false


Layout/ArgumentAlignment:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Layout/IndentationWidth:
  IgnoredPatterns:
    - '\Amodule'

Layout/LeadingCommentSpace:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false


Lint/EmptyBlock:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false


Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false


Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false


Style/AccessorGrouping:
  Enabled: false

Style/ArrayCoercion:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/BarePercentLiterals:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: false

Style/Copyright:
  Enabled: true
  Notice: '\A# Copyright \(c\) [0-9]{4} .+'
  AutocorrectNotice: '# TODO: add copyright here'

Style/DefWithParentheses:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FloatDivision:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OptionHash:
  Enabled: true

Style/PerlBackrefs:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/Send:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: false

Style/StaticClass:
  Enabled: true

Style/StringConcatenation:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
